name: Test Room Router

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout_code
        uses: actions/checkout@v4

      - name: Set-up-Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.16"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Run tests
        run: pytest tests/test_room_router.py
