name: Test Room Router

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-room-router:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10.16"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Run test_room_router.py
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest tests/test_room_router.py
